=== szykol/xml-processing/req.dtd
<!ELEMENT movies (movie+)>
<!ELEMENT movie      (title, author, (artbook|cover), year)>
<!ATTLIST movie type (science|it|action) "science">
<!ELEMENT title        (#PCDATA)>
<!ELEMENT author      (#PCDATA)>
<!ATTLIST author sex CDATA #REQUIRED>
<!ELEMENT artbook  (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ATTLIST year leap CDATA #REQUIRED>

=== szykol/xml-processing/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="test.xslt"?>
<!DOCTYPE movies SYSTEM "req.dtd">

<movies>
    <movie type="science">
        <title >Interstellar</title>
        <author sex="male">Christopher Nolan</author>
        <artbook>https://is4-ssl.mzstatic.com/image/thumb/Video5/v4/94/0b/4e/940b4e58-6628-dfb4-2565-5521c11dcdd4/pr_source.lsr/268x0w.png</artbook>
        <year leap="false">2014</year>
    </movie>
    <movie type="science">
        <title >Ex Machina</title>
        <author sex="male"> Alex Garland</author>
        <artbook>https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_.jpg</artbook>
        <year leap="false">2015</year>
    </movie>
    <movie type="science">
        <title >Obcy: 8 pasażer Nostromo</title>
        <author sex="male">Ridley Scott</author>
        <artbook>https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4oWlkMHqBxheEscXEnDKmNL6UJ1thw7_oCyjl1FrzA9HLuq2v</artbook>
        <year leap="false">1979</year>
    </movie>
    <movie type="it">
        <title >Blackhat</title>
        <author sex="male">Michael Mann</author>
        <artbook>https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTt4rbd7_Y7c1kEQFIvCA7Jo5n7JeiVzfMedFd04soFGTJYhWPfiQ</artbook>
        <year leap="false">2015</year>
    </movie>
    <movie type="it">
        <title >Snowden</title>
        <author sex="male">Oliver Stone</author>
        <artbook>https://static.rogerebert.com/uploads/movie/movie_poster/snowden-2016/large_e5vQ0HztqucuLn2FK80QD2GSkfc.jpg</artbook>
        <year leap="true">2016</year>
    </movie>
    <movie type="action">
        <title >Mission: Impossible</title>
        <author sex="male">Christopher McQuarrie</author>
        <artbook>https://ssl-gfx.filmweb.pl/po/29/76/752976/7847249.6.jpg</artbook>
        <year leap="leap">1996</year>
    </movie>
    <movie type="action">
        <title >Skyfall</title>
        <author sex="male">Sam Mendes</author>
        <artbook>https://ecsmedia.pl/c/007-james-bond-skyfall-b-iext35836596.jpg</artbook>
        <year leap="true">2012</year>
    </movie>
    <movie type="action">
        <title >Taken</title>
        <author sex="male">Pierre Morel</author>
        <artbook>https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Taken_film_poster.jpg/220px-Taken_film_poster.jpg</artbook>
        <year leap="true">2008</year>
    </movie>
    <movie type="action">
        <title >Szybcy i wściekli</title>
        <author sex="male">Rob Cohen</author>
        <artbook>https://ssl-gfx.filmweb.pl/po/05/88/30588/7145651.3.jpg</artbook>
        <year leap="false">2001</year>
    </movie>
    <movie type="action">
        <title >John Whick</title>
        <author sex="male">Chad Stahelski</author>
        <artbook>http://www.gstatic.com/tv/thumb/v22vodart/11016518/p11016518_v_v8_ag.jpg</artbook>
        <year leap="false">2014</year>
    </movie>
</movies>
